transcription-sets:
  - transcription-set:
      audio-inputs:
        - directory: Recordings/Unsorted
        - directory: Recordings/Unsorted 2021
        - directory: Recordings/Unsorted 2022
        - directory: Recordings/Unsorted 2023
        - directory: Recordings/Misc
      text-outputs:
        - directory: Transcription/Standup
          filter:
            keyword: standup
          retry:
            count: 20
            delay: 5
        - directory: Transcription/Standup
          filter:
            keyword: stand-up
          retry:
            count: 20
            delay: 5
        - directory: Transcription/Standup
          filter:
            keyword: stand
          retry:
            count: 20
            delay: 5
        - directory: Transcription/Journal
          filter:
            keyword: journal
          retry:
            count: 20
            delay: 5
        - directory: Transcription/Baby Book
          filter:
            keyword: baby
          retry:
            count: 20
            delay: 5
      deadletter:
        text-output:
          directory: Transcription/Unsorted
          retry:
            count: 20
            delay: 5
  - transcription-set:
      audio-inputs:
        - directory: Recordings/Standup Material
      text-outputs:
        - directory: Transcription/Standup
          retry:
            count: 20
            delay: 5
  - transcription-set:
      audio-inputs:
        - directory: Recordings/Journal
      text-outputs:
        - directory: Transcription/Journal
          retry:
            count: 10
            delay: 5
  - transcription-set:
      audio-inputs:
        - directory: Recordings/MMA Notes
      text-outputs:
        - directory: Transcription/MMA Notes
          retry:
            count: 20
            delay: 5
  - transcription-set:
      audio-inputs:
        - directory: Recordings/Notes on Books & Podcasts
      text-outputs:
        - directory: Transcription/Notes on Books & Podcasts
          retry:
            count: 20
            delay: 5
aggregations:
  - input:
      directory: Transcription/Standup
    output:
      filepath: Transcription/StandupAggregation.txt
      retry:
        count: 20
        delay: 5
